title = " "
baseURL = "https://asaeed.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
lastName = "Aly "
showOpenSource = false
showPublications = false
showExperience = true
showResume = true
showEducation = true
phone = "+201009547600"
profileImage = "img/1693224048735.jpeg"
favicon = "img/icon.png"
address = "Cairo, EG"
showProjects = false
showSocializations = true
firstName = "Abdullah Saeed "
email = "abdullahsaeedd6@gmail.com"
showQr = true
showBlog = true
showSkills = false

[[params.handles]]
link = "https://github.com/Abdullahsaeed10"
name = "GitHub"
icon = "fa-github-alt"

[[params.handles]]
link = "https://www.linkedin.com/in/abdullahsaeed10/"
name = "LinkedIn"

[params.google]

[params.google.analytics]
trackerID = ""

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"